import React, { useState } from "react";
import { Download } from "lucide-react";
import { Button } from "@/components/ui/button";
import html2canvas from "html2canvas";
import jsPDF from "jspdf";

interface ExportButtonProps {
    reportTitle: string;
    clubName: string;
    dateRangeStr: string;
    targetRef: React.RefObject<HTMLDivElement>;
    variant?: "default" | "outline" | "ghost";
    size?: "default" | "sm" | "lg" | "icon";
    className?: string;
    onExportComplete?: () => void;
}

export default function ExportButton({
    reportTitle,
    clubName,
    dateRangeStr,
    targetRef,
    variant = "outline",
    size = "sm",
    className,
    onExportComplete
}: ExportButtonProps) {
    const [isExporting, setIsExporting] = useState(false);

    const handleExport = async () => {
        if (!targetRef.current || isExporting) return;

        try {
            setIsExporting(true);

            // Force light theme and clean background for PDF
            const originalBg = targetRef.current.style.backgroundColor;
            targetRef.current.style.backgroundColor = "white";

            const canvas = await html2canvas(targetRef.current, {
                scale: 2,
                useCORS: true,
                logging: false,
                backgroundColor: "#ffffff",
            });

            targetRef.current.style.backgroundColor = originalBg;

            const pdf = new jsPDF("p", "mm", "a4");
            const pageWidth = pdf.internal.pageSize.getWidth();
            const pageHeight = pdf.internal.pageSize.getHeight();

            // Header
            pdf.setFont("helvetica", "bold");
            pdf.setFontSize(18);
            pdf.text(clubName, 15, 20);

            pdf.setFont("helvetica", "normal");
            pdf.setFontSize(14);
            pdf.text(reportTitle, 15, 30);

            pdf.setFontSize(10);
            pdf.setTextColor(100);
            pdf.text(`Date Range: ${dateRangeStr}`, 15, 38);
            pdf.text(`Generated on: ${new Date().toLocaleDateString()}`, 15, 43);

            // Chart Screenshot
            const imgData = canvas.toDataURL("image/jpeg", 0.95);
            const imgWidth = pageWidth - 30; // 15mm margins
            const imgHeight = (canvas.height * imgWidth) / canvas.width;

            // Simple pagination if img height exceeds page
            if (imgHeight > pageHeight - 50) {
                pdf.addImage(imgData, "JPEG", 15, 50, imgWidth, pageHeight - 60);
            } else {
                pdf.addImage(imgData, "JPEG", 15, 50, imgWidth, imgHeight);
            }

            // Footer
            pdf.setFontSize(8);
            pdf.text("Generated by Magic Nutrition Club Platform", 15, pageHeight - 10);

            // Download
            const cleanTitle = reportTitle.replace(/[^a-z0-9]/gi, '_').toLowerCase();
            pdf.save(`${clubName}-${cleanTitle}-${dateRangeStr.replace(/\s/g, "")}.pdf`);

            if (onExportComplete) onExportComplete();

        } catch (error) {
            console.error("PDF Export failed:", error);
        } finally {
            setIsExporting(false);
        }
    };

    return (
        <Button
            variant={variant}
            size={size}
            onClick={handleExport}
            disabled={isExporting}
            className={`gap-2 ${className || ""}`}
        >
            <Download className="w-4 h-4" />
            {isExporting ? "Exporting..." : "Export PDF"}
        </Button>
    );
}
